"""Relationship/acc/posts

Revision ID: 553b4dcb0ffb
Revises: 4b749a11797c
Create Date: 2024-05-13 00:11:00.442369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553b4dcb0ffb'
down_revision = '4b749a11797c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('None', 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_constraint('None', type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
